[tool.black]
line-length = 120
target-version = ["py311"] # Adjust Python version if needed
include = '\\.pyi?$'

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.bandit]
skips = ["B104", "B113", "B404", "B603", "B607"]

[tool.bandit.assert_used]
skips = ["tests/*"]

[tool.bandit.try_except_pass]
skips = ["tests/*"]
